### ISSUE TITLE
无法开始训练

### ISSUE THREAD

**Issue by OverRipeThree49** [DreamerDeo/UniSAr_text2sql#3]
按照那个pipeline.sh文件里的步骤，我完成了第一步schema linking和第二步serialization，都没有问题。
但是执行python train.py（此处省略参数）的时候，出现

FileNotFoundError: Dataset not found: train (./dataset_post/spider_sl/bin/)

的问题。但是这个目录下是有bin文件夹和那些src和tgt文件的。

测试环境为V100显卡，torch1.10版本。问题出在哪里？

**Comment by OverRipeThree49** [comment]
完整的traceback如下：

Traceback (most recent call last):
  File "/root/.virtualenvs/transformer_NLP/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/root/NLP/TEXT2SQL/UniSar/third_party/fairseq/fairseq_cli/train.py", line 473, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/root/NLP/TEXT2SQL/UniSar/third_party/fairseq/fairseq/distributed/utils.py", line 364, in call_main
    main(cfg, **kwargs)
  File "/root/NLP/TEXT2SQL/UniSar/third_party/fairseq/fairseq_cli/train.py", line 140, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/root/NLP/TEXT2SQL/UniSar/third_party/fairseq/fairseq/checkpoint_utils.py", line 229, in load_checkpoint
    epoch=1, load_dataset=True, **passthrough_args
  File "/root/NLP/TEXT2SQL/UniSar/third_party/fairseq/fairseq/trainer.py", line 530, in get_train_iterator
    data_selector=data_selector,
  File "/root/NLP/TEXT2SQL/UniSar/third_party/fairseq/fairseq/tasks/translation.py", line 353, in load_dataset
    pad_to_multiple=self.cfg.required_seq_len_multiple,
  File "/root/NLP/TEXT2SQL/UniSar/third_party/fairseq/fairseq/tasks/translation.py", line 82, in load_langpair_dataset
    "Dataset not found: {} ({})".format(split, data_path)
FileNotFoundError: Dataset not found: train (./dataset_post/spider_sl/bin/)

**Comment by DreamerDeo** [comment]
你好～
目前的文件版本只处理了`dev`数据，需要重新训练的话，https://github.com/DreamerDeo/UniSAr_text2sql/blob/b0890fa5ad0ae8c0a63d22bc4c8a5216ec002521/step1_schema_linking.py#L432 和 https://github.com/DreamerDeo/UniSAr_text2sql/blob/b0890fa5ad0ae8c0a63d22bc4c8a5216ec002521/step2_serialization.py#L9 这里对于`train`文件的预处理打开了吗？

**Comment by OverRipeThree49** [comment]
> 你好～ 目前的文件版本只处理了`dev`数据，需要重新训练的话，修改这行
> 
> https://github.com/DreamerDeo/UniSAr_text2sql/blob/b0890fa5ad0ae8c0a63d22bc4c8a5216ec002521/step1_schema_linking.py#L432
> 
> 
> https://github.com/DreamerDeo/UniSAr_text2sql/blob/b0890fa5ad0ae8c0a63d22bc4c8a5216ec002521/step2_serialization.py#L167
> 
> 
> 修改`fairseq-preprocess`函数 在这
> https://github.com/DreamerDeo/UniSAr_text2sql/blob/b0890fa5ad0ae8c0a63d22bc4c8a5216ec002521/step2_serialization.py#L9
> 
> 改成
> > ```
> > cmd = f"python -m multiprocessing_bpe_encoder \
> >           --encoder-json ./BART-large/encoder.json \
> >           --vocab-bpe ./BART-large/vocab.bpe \
> >           --inputs {generate_path}/train.src \
> >           --outputs {generate_path}/train.bpe.src \
> >           --workers 1 \
> >           --keep-empty"
> > run_command(cmd)
> > 
> > cmd = f"python -m multiprocessing_bpe_encoder \
> >         --encoder-json ./BART-large/encoder.json \
> >         --vocab-bpe ./BART-large/vocab.bpe \
> >         --inputs {generate_path}/train.tgt \
> >         --outputs {generate_path}/train.bpe.tgt \
> >         --workers 1 \
> >         --keep-empty"
> > run_command(cmd)
> > 
> > cmd = f"python -m multiprocessing_bpe_encoder \
> >         --encoder-json ./BART-large/encoder.json \
> >         --vocab-bpe ./BART-large/vocab.bpe \
> >         --inputs {generate_path}/dev.src \
> >         --outputs {generate_path}/dev.bpe.src \
> >         --workers 1 \
> >         --keep-empty"
> > run_command(cmd)
> > 
> > cmd = f"python -m multiprocessing_bpe_encoder \
> >         --encoder-json ./BART-large/encoder.json \
> >         --vocab-bpe ./BART-large/vocab.bpe \
> >         --inputs {generate_path}/dev.tgt \
> >         --outputs {generate_path}/dev.bpe.tgt \
> >         --workers 1 \
> >         --keep-empty"
> > run_command(cmd)
> > 
> > cmd = f'fairseq-preprocess --source-lang "src" --target-lang "tgt" \
> >     --trainpref {generate_path}/train.bpe \
> >     --validpref {generate_path}/dev.bpe \
> >     --destdir {generate_path}/bin \
> >     --workers 2 \
> >     --srcdict ./BART-large/dict.src.txt \
> >     --tgtdict ./BART-large/dict.tgt.txt '
> > 
> > subprocess.Popen(
> >     cmd, universal_newlines=True, shell=True,
> >     stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()
> > ```

解决了，已经成功开始训练了。感谢！
